import { faqs, levels, rates, services, site } from '../content/site.mjs';
import { formField, layout, pageHero } from './layout.mjs';

const icon = (name) => `<span class="line-icon" aria-hidden="true">${name}</span>`;
const actions = `<div class="button-row"><a class="button" href="/book/">Book a consultation</a><a class="text-link" href="/rates/">Explore our rates <span aria-hidden="true">&rarr;</span></a></div>`;

function serviceCards() {
  return services.map(([title, copy], index) => `<article class="service-card"><span class="card-number">0${index + 1}</span><h3>${title}</h3><p>${copy}</p><a class="text-link" href="/services/">Learn more <span aria-hidden="true">&rarr;</span></a></article>`).join('');
}

function pathRibbon() {
  return `<div class="learning-path" aria-label="Learning stages">${levels.map((level, index) => `<div><span>0${index + 1}</span><strong>${level}</strong></div>`).join('')}</div>`;
}

function rateSet(market) {
  const plan = rates[market];
  return `<div class="market-panel" data-market-panel="${market}"${market === 'international' ? ' hidden' : ''}>
    <article class="price-card"><p class="eyebrow">Flexible support</p><h3>Hourly Rate</h3><p class="price"><strong>${plan.hourly}</strong><span>per hour</span></p><ul><li>Assistance in one focused subject only</li><li>Lesson reinforcement and homework assistance</li><li>Exam or quiz reviews</li></ul><a class="button button-block" href="/book/">Choose hourly</a></article>
    <article class="price-card featured"><p class="eyebrow light">Consistent progress</p><h3>Monthly Rate</h3><div class="monthly-options">${plan.monthly.map(([hours, price]) => `<div><strong>${price}</strong><span>${hours}</span></div>`).join('')}</div><ul><li>Assistance in all subjects</li><li>Guidance on performance tasks, assignments, projects, summative tests, quizzes, and major examinations</li><li>Comprehensive academic support throughout the month</li></ul><a class="button button-white button-block" href="/enroll/">Choose monthly</a></article>
  </div>`;
}

function ratesSection(showIntro = true) {
  return `<section class="section rates-section"><div class="wrap">${showIntro ? '<div class="section-heading"><div><p class="eyebrow">Straightforward rates</p><h2>Choose the support that fits</h2></div><p>Switch between local and international pricing. Every plan begins with a conversation about your learner.</p></div>' : ''}<div class="market-toggle" role="group" aria-label="Choose your currency"><button class="active" type="button" data-market="local">Philippines / PHP</button><button type="button" data-market="international">International / USD</button></div>${rateSet('local')}${rateSet('international')}</div></section>`;
}

function proofStrip() {
  return `<section class="proof-strip"><div class="wrap proof-grid"><article>${icon('01')}<div><h2>Parent-informed</h2><p>Clear updates keep guardians connected to progress.</p></div></article><article>${icon('02')}<div><h2>Learner-centered</h2><p>Sessions meet students at their current pace and need.</p></div></article><article>${icon('03')}<div><h2>Online-ready</h2><p>Guided support for families in Naga and worldwide.</p></div></article></div></section>`;
}

export function homePage() {
  const body = `<section class="hero"><div class="hero-shape" aria-hidden="true"></div><div class="wrap hero-grid"><div class="hero-copy"><p class="eyebrow">Pre-school to senior high school</p><h1>Every learner can move forward.</h1><p class="lead">Patient tutors. Clear direction. Academic support shaped around your child, wherever your family learns.</p>${actions}<div class="hero-note"><strong>Local heart. Global reach.</strong><span>Face-to-face in Naga City + online worldwide</span></div></div><div class="hero-visual"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="student-card"><span class="spark">&#10022;</span><div class="portrait-placeholder"><span>LEARN</span><strong>with confidence</strong></div><div class="progress-chip"><span>Growing steadily</span><strong>One guided step at a time</strong></div></div></div></div>${pathRibbon()}</section>
  ${proofStrip()}
  <section class="section intro"><div class="wrap split"><div class="editorial-mark"><span>S</span><p>Support that sees the whole learner</p></div><div><p class="eyebrow">Why families choose Salak</p><h2>Learning support should feel clear, caring, and possible.</h2><p>We help children strengthen skills, complete schoolwork responsibly, and approach assessments with better preparation. Parents stay informed while each learner receives patient, purposeful guidance.</p><a class="text-link" href="/testimonials/">Read family stories <span aria-hidden="true">&rarr;</span></a></div></div></section>
  <section class="section about-preview"><div class="wrap split reverse"><div class="collage"><div class="collage-main"><span>STUDY</span><strong>steady progress</strong></div><div class="collage-note">Since every learner is different, every plan starts by listening.</div></div><div><p class="eyebrow">Get to know our tutorial center</p><h2>A dependable learning partner for students and parents.</h2><p>Salak Tutorial Services supports learners from pre-school to senior high school through focused tutorials, monthly academic guidance, and accessible online sessions. We combine encouragement with structure so students can build both competence and confidence.</p><ul class="check-list"><li>Age-appropriate, guided instruction</li><li>Support aligned with current schoolwork</li><li>Practical communication with parents</li></ul><a class="button button-outline" href="/about/">Discover who we are</a></div></div></section>
  <section class="section services-preview"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">What we help with</p><h2>Academic services for every stage</h2></div><p>From first learning routines to senior high requirements, support grows with the student.</p></div><div class="service-grid">${serviceCards()}</div></div></section>
  <section class="section online-preview"><div class="wrap online-grid"><div><p class="eyebrow light">Online tutoring worldwide</p><h2>A safe, guided online learning experience</h2><p>Families overseas can access the same patient, parent-informed support. We work from the learner's school materials and goals, adapting sessions to different curricula without making one-size-fits-all promises.</p><div class="stat-row"><div><strong>1:1</strong><span>focused guidance</span></div><div><strong>4</strong><span>learning stages</span></div><div><strong>2</strong><span>currencies</span></div></div><a class="button button-white" href="/online-tutoring/">Explore online tutoring</a></div><div class="online-panel"><span class="panel-tag">A session built around your child</span><ol><li><span>01</span>Tell us the learning need</li><li><span>02</span>Confirm the right schedule</li><li><span>03</span>Meet the tutor online</li><li><span>04</span>Keep parents informed</li></ol></div></div></section>
  ${ratesSection()}
  <section class="section final-proof"><div class="wrap narrow center"><p class="eyebrow">Encouragement with direction</p><h2>Progress begins when a learner feels understood.</h2><p class="lead">Whether your child needs steady monthly support or one focused review session, we are ready to listen and help map the next step.</p>${actions}</div></section>`;
  return layout({ title: 'Home', path: '/', body, pageClass: 'home' });
}

export function aboutPage() {
  const body = `${pageHero('Who we are', 'A tutorial center built around steady progress.', 'Salak brings patient instruction, clear academic guidance, and practical parent communication together in one supportive learning environment.', actions)}<section class="section"><div class="wrap split"><div><p class="eyebrow">Our purpose</p><h2>Helping learners believe they can do the next hard thing.</h2><p>We are here to make schoolwork feel more manageable and learning feel more meaningful. Our tutors guide students from pre-school through senior high school with warmth, consistency, and respect for their individual pace.</p><p>At our Naga City center and in online sessions worldwide, we start by understanding the learner's needs, current school demands, and family goals.</p></div><div class="values-stack"><article><span>01</span><h3>Listen first</h3><p>We learn what the student and parent need before shaping support.</p></article><article><span>02</span><h3>Guide clearly</h3><p>We break work into understandable, achievable steps.</p></article><article><span>03</span><h3>Build confidence</h3><p>We recognize progress while strengthening independent learning habits.</p></article></div></div></section>${proofStrip()}<section class="section"><div class="wrap">${pathRibbon()}<div class="center narrow spacing-top"><h2>One learning partner from early years through SHS.</h2><p>Our services grow with the learner, from foundational routines to focused subject support and demanding performance tasks.</p></div></div></section>`;
  return layout({ title: 'Who We Are', path: '/about/', body });
}

export function servicesPage() {
  const body = `${pageHero('Academic services', 'The right support for the work in front of them.', 'Choose focused hourly help or comprehensive monthly guidance, delivered face-to-face in Naga City or online.', actions)}<section class="section"><div class="wrap service-grid large">${serviceCards()}</div></section><section class="section soft"><div class="wrap split"><div><p class="eyebrow">Hourly tutorials</p><h2>Focused help for one subject.</h2><p>Ideal when a learner needs lesson reinforcement, homework assistance, or a guided review before a quiz or examination.</p></div><div><p class="eyebrow">Monthly support</p><h2>Whole-month guidance across all subjects.</h2><p>Designed for families who need dependable assistance with everyday lessons, performance tasks, assignments, projects, summative tests, quizzes, and major examinations.</p></div></div></section>`;
  return layout({ title: 'Academic Services', path: '/services/', body });
}

export function onlinePage() {
  const body = `${pageHero('For international families', 'Online tutoring with a local sense of care.', 'Personalized live sessions for learners abroad, based on their own curriculum, school materials, schedule, and academic goals.', actions)}<section class="section"><div class="wrap online-steps"><article><span>01</span><h2>Share the context</h2><p>Tell us the learner's year level, country, school curriculum, current lessons, and the support you want.</p></article><article><span>02</span><h2>Plan the match</h2><p>We confirm availability, a suitable tutor, session format, and a practical schedule across time zones.</p></article><article><span>03</span><h2>Learn live</h2><p>The tutor guides the learner through shared materials, explanations, practice, and questions in real time.</p></article><article><span>04</span><h2>Stay connected</h2><p>Parents receive clear communication about arrangements and learning direction.</p></article></div></section><section class="section dark"><div class="wrap split"><div><p class="eyebrow light">International rates</p><h2>Simple USD pricing for online families.</h2><p>Start with one focused subject at USD 8 per hour, or choose a monthly plan from USD 80.</p><a class="button button-white" href="/rates/">See all international rates</a></div><div class="timezone-card"><span>WORLDWIDE</span><strong>Your materials.<br>Your goals.<br>Guided together.</strong></div></div></section>`;
  return layout({ title: 'Online Tutoring', path: '/online-tutoring/', body });
}

export function ratesPage() {
  const body = `${pageHero('Rates', 'Clear options for focused help or ongoing support.', 'View Philippine and international rates below. We confirm the learner plan and schedule before payment.', '<div class="button-row"><a class="button" href="/book/">Ask about availability</a></div>')}${ratesSection(false)}<section class="section soft"><div class="wrap narrow"><h2>Before you choose</h2><div class="faq-list"><details open><summary>When is hourly support the better fit?</summary><p>Choose hourly tutoring for assistance in one focused subject only, particularly for lesson reinforcement, homework assistance, and exam or quiz reviews.</p></details><details><summary>What makes monthly support different?</summary><p>Monthly plans provide assistance in all subjects, with comprehensive academic support throughout the month and guidance on performance tasks, assignments, projects, summative tests, quizzes, and major examinations.</p></details><details><summary>Are tutor and schedule guaranteed after payment?</summary><p>No. Please wait for our schedule confirmation before paying. Availability depends on the learner's needs, tutor match, and agreed timetable.</p></details></div></div></section>`;
  return layout({ title: 'Rates', path: '/rates/', body });
}

export function testimonialsPage() {
  const body = `${pageHero('Family stories', 'The moments of progress that matter.', 'This page is ready for verified stories from Salak parents and learners. We will publish testimonials only with permission.', actions)}<section class="section"><div class="wrap quote-grid"><blockquote><p>&ldquo;Add a short, specific parent story here after consent is received.&rdquo;</p><footer>Verified parent testimonial</footer></blockquote><blockquote><p>&ldquo;Share what changed for the learner, not just a general compliment.&rdquo;</p><footer>Verified learner story</footer></blockquote><blockquote><p>&ldquo;A useful story can describe confidence, consistency, or a clearer learning routine.&rdquo;</p><footer>Verified family experience</footer></blockquote></div></section>`;
  return layout({ title: 'Family Stories', path: '/testimonials/', body });
}

function formShell({ type, intro, fields, submit = 'Send request', note }) {
  return `<section class="section"><div class="wrap form-layout"><aside><p class="eyebrow">What happens next</p><h2>We review before we confirm.</h2><ol class="side-steps"><li><span>01</span>We read the learner details.</li><li><span>02</span>We check the right tutor and schedule.</li><li><span>03</span>We reply by email with the next step.</li></ol><p class="privacy-note">Your information is used only to respond to this request and provide tutorial services.</p></aside><form class="lead-form" data-form="${type}" action="/api/${type}" method="post"><label class="honeypot" aria-hidden="true"><span>Website</span><input name="website" tabindex="-1" autocomplete="off"></label><p>${intro}</p><div class="field-grid">${fields}</div>${note || ''}<label class="consent"><input type="checkbox" name="consent" required><span>I confirm that I am the parent or authorized guardian and consent to Salak using these details to respond to this request.</span></label><button class="button button-block" type="submit">${submit}</button><p class="form-status" role="status" aria-live="polite"></p></form></div></section>`;
}

const guardianFields = () => `${formField({ label: 'Parent or guardian name', name: 'guardianName', autocomplete: 'name' })}${formField({ label: 'Email address', name: 'email', type: 'email', autocomplete: 'email' })}${formField({ label: 'Mobile / WhatsApp', name: 'phone', type: 'tel', autocomplete: 'tel' })}${formField({ label: 'Country', name: 'country', autocomplete: 'country-name' })}`;
const learnerFields = (includeUnsure = true) => `${formField({ label: 'Learner name', name: 'learnerName' })}${formField({ label: 'Year level', name: 'yearLevel', options: levels })}${formField({ label: 'Preferred setup', name: 'deliveryMode', options: ['Face-to-face in Naga City', 'Online'] })}${formField({ label: 'Preferred plan', name: 'plan', options: ['Hourly', 'Monthly - 20 hours', 'Monthly - 30 hours', 'Monthly - 40 hours', ...(includeUnsure ? ['Not sure yet'] : [])] })}`;

export function bookPage() {
  const schedule = `${formField({ label: 'Preferred date', name: 'preferredDate', type: 'date' })}${formField({ label: 'Preferred time', name: 'preferredTime', type: 'time' })}${formField({ label: 'Time zone', name: 'timeZone', placeholder: 'e.g. Asia/Manila' })}`;
  const body = `${pageHero('Book a consultation', 'Tell us where your learner needs support.', 'There is no payment at this stage. We will review the request and contact you about availability.')} ${formShell({ type: 'bookings', intro: 'Fields marked with * are required. Your preferred time is a request until we confirm it.', fields: guardianFields() + learnerFields() + schedule + '<label class="full"><span>What would you like help with? *</span><textarea name="learningNeeds" rows="5" required></textarea></label>', submit: 'Request a consultation' })}`;
  return layout({ title: 'Book a Consultation', path: '/book/', body });
}

export function enrollPage() {
  const body = `${pageHero('Online enrollment', 'Start your learner profile.', 'Complete this form after reviewing our services and rates. Enrollment is confirmed only after tutor, schedule, and payment arrangements are approved.')} ${formShell({ type: 'enrollments', intro: 'Please provide accurate guardian and learner information.', fields: guardianFields() + learnerFields(false) + `${formField({ label: 'School', name: 'school', required: false })}${formField({ label: 'Curriculum', name: 'curriculum', required: false })}<label class="full"><span>Subjects and current learning needs *</span><textarea name="learningNeeds" rows="5" required></textarea></label>`, submit: 'Submit enrollment' })}`;
  return layout({ title: 'Enroll Online', path: '/enroll/', body });
}

export function faqPage() {
  const body = `${pageHero('Frequently asked questions', 'Helpful answers before you begin.', 'If your question is not covered here, send us a message and we will be glad to help.', '<div class="button-row"><a class="button" href="/contact/">Ask a question</a></div>')}<section class="section"><div class="wrap narrow faq-list">${faqs.map(([question, answer], index) => `<details${index === 0 ? ' open' : ''}><summary>${question}</summary><p>${answer}</p></details>`).join('')}</div></section>`;
  return layout({ title: 'FAQs', path: '/faq/', body });
}

export function contactPage() {
  const fields = `${formField({ label: 'Your name', name: 'name', autocomplete: 'name' })}${formField({ label: 'Email address', name: 'email', type: 'email', autocomplete: 'email' })}${formField({ label: 'Mobile / WhatsApp', name: 'phone', type: 'tel', required: false })}<label class="full"><span>Your message *</span><textarea name="message" rows="6" required></textarea></label>`;
  const body = `${pageHero('Contact Salak', 'Let us talk about the next learning step.', 'Send an inquiry online or visit our tutorial center at 3 Dover Street, J. Miranda Avenue, Naga City, Philippines.')} ${formShell({ type: 'inquiries', intro: 'We normally respond through the contact details you provide.', fields, submit: 'Send inquiry' })}`;
  return layout({ title: 'Contact', path: '/contact/', body });
}

export function paymentPage() {
  const fields = `${formField({ label: 'Enrollment ID', name: 'enrollmentId', placeholder: 'Provided after confirmation' })}${formField({ label: 'Parent or guardian name', name: 'guardianName', autocomplete: 'name' })}${formField({ label: 'Email address', name: 'email', type: 'email', autocomplete: 'email' })}${formField({ label: 'Learner name', name: 'learnerName' })}${formField({ label: 'Amount paid', name: 'amount', type: 'number' })}${formField({ label: 'Payment reference number', name: 'referenceNumber' })}${formField({ label: 'Payment date', name: 'paymentDate', type: 'date' })}`;
  const body = `${pageHero('Local payment reference', 'Tell us after your payment is sent.', 'Use this form only after Salak has confirmed the learner schedule and provided the correct local payment instructions. No receipt upload is required.')} ${formShell({ type: 'payment-references', intro: 'We verify the reference against the agreed enrollment details.', fields, submit: 'Submit payment reference', note: '<div class="notice full"><strong>Important:</strong> A reference submission is not an automatic payment confirmation. We will verify it and reply by email.</div>' })}`;
  return layout({ title: 'Submit Payment Reference', path: '/payment/local/', body });
}

export function policyPage(type) {
  const pages = {
    privacy: ['Privacy Policy', 'How we handle your information.', `<h2>Information we collect</h2><p>We collect details submitted through inquiry, booking, enrollment, and payment reference forms so we can respond, arrange tutorial services, and keep appropriate service records.</p><h2>How we use it</h2><p>Information is used for communication, learner support planning, scheduling, payment verification, safeguarding, and service administration. We do not sell personal information.</p><h2>Retention</h2><p>General inquiries may be retained for up to 12 months. Enrollment and transaction records may be retained for up to 24 months or longer when required by law. You may contact us to request access or correction.</p><h2>Children's information</h2><p>A parent or authorized guardian must submit and consent to the use of information for learners under 18.</p>`],
    terms: ['Terms of Service', 'Clear expectations for tutorial arrangements.', `<h2>Service confirmation</h2><p>Submitting a form does not guarantee enrollment, tutor availability, or a specific schedule. Services begin only after Salak confirms the plan and arrangements.</p><h2>Learner participation</h2><p>Families should provide accurate information, relevant learning materials, and a suitable learning environment. Tutors guide learning but do not complete graded work on a learner's behalf.</p><h2>Scheduling</h2><p>Session schedules, rescheduling windows, and tutor arrangements are confirmed directly with the parent or guardian.</p><h2>Changes</h2><p>Salak may update these terms as services develop. Material changes will be reflected on this page.</p>`],
    payment: ['Payment Policy', 'Payment follows a confirmed learning plan.', `<h2>Pay only after confirmation</h2><p>Wait for Salak to confirm tutor availability, schedule, plan, amount, and the official payment channel before sending funds.</p><h2>Reference verification</h2><p>Philippine families may submit the payment reference number through this site. A submitted reference is reviewed and is not automatic proof of a completed payment.</p><h2>International payments</h2><p>International families receive USD payment instructions after their tutorial arrangement is confirmed.</p><h2>Changes and refunds</h2><p>Any rescheduling, credit, or refund terms that apply to a plan will be communicated before payment. Contact Salak promptly if a payment issue occurs.</p>`],
  };
  const [title, lead, content] = pages[type];
  const path = type === 'payment' ? '/payment-policy/' : `/${type}/`;
  const contact = site.email ? `<a href="mailto:${site.email}">${site.email}</a>` : '<a href="/contact/">our contact form</a>';
  return layout({ title, path, body: `${pageHero('Legal and service information', title, lead)}<section class="section"><div class="wrap narrow prose">${content}<h2>Contact</h2><p>Questions about this policy may be sent through ${contact}.</p></div></section>` });
}

export function thankYouPage() {
  return layout({ title: 'Thank You', path: '/thank-you/', body: `<section class="thank-you"><div class="wrap narrow center"><span class="success-mark">&#10003;</span><p class="eyebrow">Request received</p><h1>Thank you for reaching out.</h1><p class="lead">We will review the details and reply using the email address you provided.</p><div class="button-row center"><a class="button" href="/">Return home</a><a class="text-link" href="/faq/">Read the FAQs <span aria-hidden="true">&rarr;</span></a></div></div></section>` });
}
